### ISSUE TITLE
SSL Errors on goodreads communication

### ISSUE THREAD

**Issue by SenorSmartyPants** [linuxserver/docker-lazylibrarian#59]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

No Errors should be logged

Check https://lazylibrarian.gitlab.io/faq/#ssl-on-ubuntu-20042010 for possible solutions.

## Current Behavior

many log entries like this
```
lazylibrarian       | 2021-10-09T19:58:53.670668738Z   InsecureRequestWarning,
lazylibrarian       | 2021-10-09T19:58:53.670683905Z /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.goodreads.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

## Steps to Reproduce

1. Use Goodreads as info source. Config->Importing->Book Information
2. Add/Update Author
3. view log

## Environment
**OS:** Arbmian
**CPU architecture:** arm64
**How docker service was installed:** Armbian-config

## Command used to create docker container (run/create/compose/screenshot)

```
  ll:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=100
    volumes:
      - /mnt/seagate4TB/appdata/lazylibrarian:/config
      - /mnt/storage:/storage
    ports:
      - 5299:5299
    restart: unless-stopped
```
