### ISSUE TITLE
Latest LL / calibrweb integration failing because of missing GNUC libraries

### ISSUE THREAD

**Issue by devilsangel360live** [linuxserver/docker-lazylibrarian#62]
Until so far, I was enjoying LL and Calibre-web communicate seamlessly behind docker images (no Calibre setup). I was using DOCKER_MODS= linuxserver/calibre-web:calibre for the LL container.
However, I recently updated LL with the latest release and had to update the DOCKER_MOD to linuxserver/mods:universal-calibre because the old mod is not supported anymore.
In LL config, I have Calibredb import program as /usr/bin/calibredb as earlier but when I test calibredb, I get the following error:
calibredb communication failed: run_script exception: FileNotFoundError [Errno 2] No such file or directory: '/usr/bin/calibredb': '/usr/bin/calibredb'Close
Needless to say, none of my ebooks auto downloaded through Jackett are being imported to the calibredb and obviously not showing up on the calibreweb frontend
Any idea what can be causing this issue? Happy to share logs
My setup:
OMV6, Calibreweb docker container from linuxserver, LL container from linuxserver with the calibreweb mod.

I posted this on Lazylibrian Gitlab https://gitlab.com/LazyLibrarian/LazyLibrarian/-/issues/2474 and did some debugging based on Phil's suggestions:
1. Changed the location of calibredb from /usr/bin/calibredb to /app/calibre/caliberdb
2. Rebuilt container rebuilt the container with the latest image - on version Current Version: 02db8f6e133a4e3f0cdf942d5c36ff64ab6af039 : Latest Version: 02db8f6e133a4e3f0cdf942d5c36ff64ab6af039rebuilt the container with the latest image - on version Current Version: [02db8f6e](https://github.com/LazyLibrarian/LazyLibrarian/-/commit/02db8f6e133a4e3f0cdf942d5c36ff64ab6af039) : Latest Version: [02db8f6e](https://github.com/LazyLibrarian/LazyLibrarian/-/commit/02db8f6e133a4e3f0cdf942d5c36ff64ab6af039)

Now, I receive the following errors because of missing GNU C libraries

calibredb communication failed: /app/calibre/bin/calibredb: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /app/calibre/lib/libpython3.10.so.1.0) /app/calibre/bin/calibredb: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /app/calibre/lib/libpython3.10.so.1.0) /app/calibre/bin/calibredb: /lib/x86_64-linux-gnu/libc.so.6: version \`GLIBC_2.28' not found (required by /app/calibre/lib/libpython3.10.so.1.0)

I checked the container with "ldd --version" and found that I only have GLIBC 2.27 installed. Should the docker image come with the updated GLIBC versions?

I also checked my OMV install and it already comes with version 2.31 installed: root@omv6:\~# ldd --version ldd (Debian GLIBC 2.31-13) 2.31

Does the docker image need to be updated with the latest libraries? Can you please help?

**Comment by thespad** [comment]
Both the mod and lazylibrarian are using the Focal base which ships with 2.31 so I'm not sure where 2.27 is coming from.

I've just spun up a brand new LL container with the mod installed and
```
# ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.7) 2.31
```
And `calibredb` runs fine
```
# /app/calibre/calibredb 
Usage: calibredb command [options] [arguments]

calibredb is the command line interface to the calibre books database.
```

**Comment by devilsangel360live** [comment]
This is from a console connected to the docker image:

```
root@4043a4457a17:/# /app/calibre/calibredb
/app/calibre/bin/calibredb: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /app/calibre/lib/libpython3.10.so.1.0)
/app/calibre/bin/calibredb: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /app/calibre/lib/libpython3.10.so.1.0)
/app/calibre/bin/calibredb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/calibre/lib/libpython3.10.so.1.0)

root@4043a4457a17:/# ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
```

And this is my docker compose:

```
---
version: "2.1"
services:
  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /srv/dev-disk-by-uuid-44557c8d-25b0-4e66-9291-1fddc461a068/Config2/LazyLibrarian:/config
      - /srv/dev-disk-by-uuid-44557c8d-25b0-4e66-9291-1fddc461a068/Torrents:/downloads
      - /srv/dev-disk-by-uuid-44557c8d-25b0-4e66-9291-1fddc461a068/Books:/books #optional
      - /srv/dev-disk-by-uuid-44557c8d-25b0-4e66-9291-1fddc461a068/Audiobooks:/audiobooks
    ports:
      - 5299:5299
    restart: unless-stopped
```

Am I using a wrong image?
